### ISSUE TITLE
Feature: Acceleration support for all motion

### ISSUE THREAD

**Issue by MSDimos** [rainbowhxch/accelerated-jk.nvim#1]
As the document mentioned, this plugin only supports four motions: `j`, `k`, `gj`, `gk`.

But for most of (Neo)Vim users, there are many others motions been used such as `e`, `b`, etc. Even some custom commands, for example, I use `<C-J>` to scroll down `5` lines.

I have read the source code, I noticed that just need to change a piece of code, it can support other motions. See pic below:

![image](https://user-images.githubusercontent.com/23169141/179885528-3e51f10f-d4de-416d-bfee-5c15d3845e3b.png)

After that, I can accelarate my `e` and `b` now!

![image](https://user-images.githubusercontent.com/23169141/179910659-2089fe24-f3f0-48aa-8db8-47d27a7fe0ec.png)

It's better be a feature request, but I can only open an issue here, sorry for it.

**Comment by rainbowhxch** [comment]
@MSDimos Hi, what a great idea! I appreciate it, although not so accelerated-"jk" 😆 . I've tried it and I think it's perfectly feasible and acceptable. I will add such feature later.  Thank you for the in-depth check work of the code.

**Comment by rainbowhxch** [comment]
Feature implemented(16ba3443c0720a0a1c8f7f31146729b1f406b037), check out the [acceleration_motions](https://github.com/rainbowhxch/accelerated-jk.nvim#configuration) configuration item to apply it.
