### ISSUE TITLE
how to use 16ba344? 

### ISSUE THREAD

**Issue by mvmx3** [rainbowhxch/accelerated-jk.nvim#2]
It's my config 

	require("accelerated-jk").setup({
		mode = "time_driven",
		acceleration_motions = { "h", "l", "e", "b" },
		acceleration_limit = 150,
		-- acceleration_table = { 0 },
		acceleration_table = { 7, 12, 17, 21, 24, 26, 28, 30 },
		-- when 'enable_deceleration = true', 'deceleration_table = { {200, 3}, {300, 7}, {450, 11}, {600, 15}, {750, 21}, {900, 9999} }'
		enable_deceleration = false,
		deceleration_table = { { 150, 9999 } },
	})
but my nmap is not "h, l, e ,b". It's only following:

:nmap

n  \<Plug\>(accelerated_jk_gk) * \<Cmd\>lua require'accelerated-jk'.move_to('gk')\<CR\>                                                                                                                                 
n  \<Plug\>(accelerated_jk_gj) * \<Cmd\>lua require'accelerated-jk'.move_to('gj')\<CR\>                                                                                                                                 
n  \<Plug\>(accelerated_jk_k) * \<Cmd\>lua require'accelerated-jk'.move_to('k')\<CR\>                                                                                                                                   
n  \<Plug\>(accelerated_jk_j) * \<Cmd\>lua require'accelerated-jk'.move_to('j')\<CR\>      

not others \<Plug\>(accelerated_jk...   * \<Cmd\>lua require'accelerated-jk'.move_to(...) \<CR\>

**Comment by rainbowhxch** [comment]
@mjkx5 According to your configuration, in addition to the above, there should be the following:
```vim
n  h           * <Cmd>lua require'accelerated-jk'.move_to('h')<CR>
n  l           * <Cmd>lua require'accelerated-jk'.move_to('l')<CR>
n  e           * <Cmd>lua require'accelerated-jk'.move_to('e')<CR>
n  b           * <Cmd>lua require'accelerated-jk'.move_to('b')<CR>
```
The configuration works well on my neovim. And I use nightly version. You should check whether other maps have overwritten the items of `h`/`l`/`e`/`b` (e.g. `:nmap h`).

**Comment by mvmx3** [comment]
I alter my config and code for debug:

	require("accelerated-jk").setup({
		mode = "time_driven",
		acceleration_motions = { "h" },
		acceleration_limit = 150,
		-- acceleration_table = { 0 },
		acceleration_table = { 7, 12, 17, 21, 24, 26, 28, 30 },
		-- when 'enable_deceleration = true', 'deceleration_table = { {200, 3}, {300, 7}, {450, 11}, {600, 15}, {750, 21}, {900, 9999} }'
		enable_deceleration = false,
		deceleration_table = { { 150, 9999 } },
	})
--------------------

```text
diff --git a/lua/accelerated-jk/init.lua b/lua/accelerated-jk/init.lua
index cefbe21..5c2956c 100644
--- a/lua/accelerated-jk/init.lua
+++ b/lua/accelerated-jk/init.lua
@@ -16,7 +16,8 @@ local create_keymaps = function(config)
   for _, motion in ipairs(config.acceleration_motions) do
     vim.api.nvim_set_keymap(
       'n',
-      motion,
+      -- motion,
+      '<Plug>(accelerated_jk_h)',
       string.format("<CMD>lua require'accelerated-jk'.move_to('%s')<CR>", motion),
       { silent = true, noremap = true }
     )
@@ -33,18 +34,6 @@ local create_keymaps = function(config)
     "<CMD>lua require'accelerated-jk'.move_to('k')<CR>",
     { silent = true, noremap = true }
   )
-  vim.api.nvim_set_keymap(
-    'n',
-    '<Plug>(accelerated_jk_gj)',
-    "<CMD>lua require'accelerated-jk'.move_to('gj')<CR>",
-    { silent = true, noremap = true }
-  )
-  vim.api.nvim_set_keymap(
-    'n',
-    '<Plug>(accelerated_jk_gk)',
-    "<CMD>lua require'accelerated-jk'.move_to('gk')<CR>",
-    { silent = true, noremap = true }
-  )
 end
```

**Comment by mvmx3** [comment]
but I input :nmap 

only get:
```text
n  <Plug>(accelerated_jk_k) * <Cmd>lua require'accelerated-jk'.move_to('k')<CR>                                                                                                                                   
n  <Plug>(accelerated_jk_j) * <Cmd>lua require'accelerated-jk'.move_to('j')<CR>  
```

**Comment by mvmx3** [comment]
because I am unfamiliar  with lua, I  can't get real reason .

**Comment by mvmx3** [comment]
accelerated-jk.nvim version is  38bbbf9258aab876906588ea979901ed3ed569c6

nvim version 

NVIM v0.7.2
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info

**Comment by mvmx3** [comment]
It seems my fault, It can't understand config.acceleration_motions.

**Comment by mvmx3** [comment]
how to print my config use lua, because I can't locate fault .

**Comment by rainbowhxch** [comment]
@mjkx5 There is something wrong with your understanding of `<Plug>(accelerated_jk_j)` and `<Plug>(accelerated_jk_k)`. They are available without configuration and just for convenient mapping purposes, see `:h <Plug>`. So there is no internal mapping of `<Plug>(accelerated_jk_h)`. According to your description, I guess your Lua configuration is in the wrong place, so this configuration does not take effect at all.

> how to print my config use lua, because I can't locate fault .

```diff
diff --git a/lua/accelerated-jk/init.lua b/lua/accelerated-jk/init.lua
index cefbe21..e9de2cf 100644
--- a/lua/accelerated-jk/init.lua
+++ b/lua/accelerated-jk/init.lua
@@ -61,6 +61,7 @@ M.setup = function(opts)
   end

   local config = conf_module.merge_config(opts)
+  print(vim.inspect(config))
   driver = create_driver(config)
   create_keymaps(config)
```
